### ISSUE TITLE
Better styling compatibility

### ISSUE THREAD

**Issue by arturoribes** [keiya01/react-simple-wheel-picker#33]
Hi! Very nice package, I only have found yours, so congrats!

I would like to have more control over the styling of the component. For example, be able to remove the check mark, control the margins or paddings, etc... It would be nice to have visualization and control decoupled so one can customize visualization while using your control mechanisms.

**Comment by keiya01** [comment]
Thank you for the comment.

Your suggestions are very nice!
I will improve this package with your opinion. 

And it would be helpful if you could put out a PR, if you interest my package.

**Comment by keiya01** [comment]
If you want to control `margin` or `padding`, you can use `itemHeight` or `width` props. :)
